-- KNOOVI production database schema for Supabase
create table if not exists products (
  id bigint primary key generated by default as identity,
  name text not null,
  category text not null,
  price integer not null default 0,
  description text default '',
  image_url text default '',
  stock integer not null default 0,
  rating numeric(2,1) default 0,
  review_count integer default 0,
  colors jsonb default '[]'::jsonb,
  sizes jsonb default '[]'::jsonb,
  personalizable boolean default false,
  new_in boolean default false,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists banners (
  id bigint primary key generated by default as identity,
  title text not null,
  subtitle text default '',
  image_url text default '',
  button_text text default 'Shop Now',
  button_link text default '#shop',
  coupon_code text default '',
  active boolean default false,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists coupons (
  id bigint primary key generated by default as identity,
  code text unique not null,
  discount_type text not null check (discount_type in ('percent','fixed')),
  value numeric not null,
  minimum_order numeric default 0,
  maximum_discount numeric,
  usage_limit integer,
  used_count integer default 0,
  active boolean default true,
  expires_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  created_at timestamptz default now()
);

create table if not exists addresses (
  id bigint primary key generated by default as identity,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  address_line text,
  city text,
  state text,
  pincode text,
  is_default boolean default false,
  created_at timestamptz default now()
);

create table if not exists orders (
  id bigint primary key generated by default as identity,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text,
  customer_phone text,
  shipping_address jsonb,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric default 0,
  discount numeric default 0,
  shipping_fee numeric default 0,
  total numeric default 0,
  payment_status text default 'pending',
  order_status text default 'new',
  payment_reference text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists reviews (
  id bigint primary key generated by default as identity,
  user_id uuid references auth.users(id) on delete set null,
  product_id bigint references products(id) on delete cascade,
  rating integer check (rating between 1 and 5),
  review_text text,
  approved boolean default false,
  created_at timestamptz default now()
);

create table if not exists custom_requests (
  id bigint primary key generated by default as identity,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  occasion text,
  budget numeric,
  required_date date,
  message text,
  reference_image_url text,
  status text default 'new',
  created_at timestamptz default now()
);

alter table products enable row level security;
alter table banners enable row level security;
alter table coupons enable row level security;
alter table orders enable row level security;
alter table addresses enable row level security;
alter table reviews enable row level security;
alter table custom_requests enable row level security;

create policy "public can view active products" on products for select using (active = true);
create policy "public can view active banners" on banners for select using (active = true);
create policy "users view own orders" on orders for select using (auth.uid() = user_id);
create policy "users create own orders" on orders for insert with check (auth.uid() = user_id);
create policy "users view own addresses" on addresses for select using (auth.uid() = user_id);
create policy "users manage own addresses" on addresses for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users view approved reviews" on reviews for select using (approved = true);
